# Generated by Django 5.0 on 2023-12-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='job',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='JobNames',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
