# Generated by Django 5.0 on 2023-12-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='job',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='JobNames',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
