# Generated by Django 5.0 on 2023-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_freelancer_job_remove_freelancer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_freelancer',
        ),
    ]
